#!/usr/bin/node
/*
 * compiler <https://github.com/1024sparrow/compiler>
 * Утилита для многоэтапной сборки проектов.
 * Utility for multistage project building.
 * 
 * Авторское право (c) 2017-2020, Борис Васильев.
 * Публикуется под лицензией MIT.
 *
 * Copyright (c) 2017-2020, Boris Vasilyev.
 * Released under the MIT license.
 */

{%% body.js %%}
